import type { Metadata } from "next";
import "./globals.css";
// Enable bootstrap JS and Icons
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { BootstrapClientInit } from "@/components/index";
import { Navbar, Footer } from "@/app/index";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="main-content">{children}</main>
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
